- name: Run apt update & upgrade
  hosts: all
  user: ubuntu
  become: yes

  tasks:
    - name: Running apt update & upgrade
      apt:
        name: "*"
        state: latest
        update_cache: yes
