- name: Import CSV File to Table
  hosts: database
  user: root
  become: yes

  vars_prompt:
    - name: csv
      prompt: Enter the name of the CSV file
      private: no
      default: students.csv

    - name: sql
      prompt: Enter the name of the SQL file
      private: no
      default: create_students_table.sql

    - name: database
      prompt: Enter the name of the database
      private: no
      default: cdrpl

    - name: table
      prompt: Enter the table name that the CSV file will be imported into
      private: no
      default: students

  tasks:
    - name: Copying CSV file to database instance
      copy:
        src: "{{ csv }}"
        dest: /var/lib/mysql-files
        owner: root
        group: root

    - name: Copying SQL file to the database instance
      copy:
        src: "{{ sql }}"
        dest: /var/lib/mysql-files
        owner: root
        group: root

    - name: Running the SQL file
      community.mysql.mysql_db:
        name: "{{ database }}"
        state: import
        target: /var/lib/mysql-files/{{ sql }}
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Importing the CSV file into the {{ table }} table
      community.mysql.mysql_query:
        login_db: "{{ database }}"
        query: LOAD DATA INFILE '/var/lib/mysql-files/{{ csv }}' INTO TABLE {{ table }} FIELDS TERMINATED BY ',' IGNORE 1 ROWS
        login_unix_socket: /var/run/mysqld/mysqld.sock
