- name: Initialize Apache Spark Master
  hosts: master
  user: ubuntu
  become: yes

  vars_prompt:
    - name: docker_image
      prompt: "Enter the name of the Apache Spark Docker image"
      private: no
      default: justinshyi/spark-custom

    - name: node_ips
      prompt: "Enter the private IP addresses of the worker nodes, separated by spaces"
      private: no

  tasks:
    - set_fact:
        node_ips: "{{ node_ips.split(' ') }}"

    - name: Running apt update
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Installing required apt packages
      apt:
        name:
          - openjdk-8-jdk
          - scala
        state: latest

    - name: Copying id_rsa
      copy:
        src: /root/.ssh/id_rsa
        dest: /home/ubuntu/.ssh
        owner: ubuntu
        group: ubuntu
        mode: "0600"

    - name: Copying mysql-connector-j
      copy:
        src: /root/mysql-connector-j_8.0.31-1ubuntu22.04_all.deb
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu

    - name: Installing mysql-connector-j
      apt:
        deb: /home/ubuntu/mysql-connector-j_8.0.31-1ubuntu22.04_all.deb

    - name: Deleting mysql-connector-j_8.0.31-1ubuntu22.04_all.deb
      file:
        path: /home/ubuntu/mysql-connector-j_8.0.31-1ubuntu22.04_all.deb
        state: absent

    - name: Downloading Docker install script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh

    - name: Installing Docker
      shell: DRY_RUN=1 sudo sh ./get-docker.sh

    - name: Deleting Docker install script
      file:
        path: /home/ubuntu/get-docker.sh
        state: absent

    - name: Running the Docker image "{{ docker_image }}"
      shell: docker run -d --name custom-spark {{ docker_image }}

    - name: Copying spark from running Docker container
      shell: docker cp custom-spark:/opt/spark /opt/spark

    - name: Deleting running Docker container
      shell: docker rm -f custom-spark

    - name: Changing ownership of /opt/spark
      file:
        path: /opt/spark
        owner: ubuntu
        group: ubuntu

    - name: Adding spark to path in /home/ubuntu/.profile
      lineinfile:
        path: /home/ubuntu/.profile
        line: export PATH=/opt/spark/bin:$PATH

    - name: Creating Apache Spark slaves file
      file:
        path: /opt/spark/conf/slaves
        state: touch
        owner: ubuntu
        group: ubuntu
        mode: u=rw,g=r,o=r

    - name: Adding worker IPs to Apache Spark slaves file
      lineinfile:
        path: /opt/spark/conf/slaves
        line: "{{ item }}"
      loop: "{{ node_ips }}"

    - name: Creating symbolic link for MySQL Connector J
      shell: ln -sf /usr/share/java/mysql-connector* /opt/spark/jars

    - name: Rebooting the master instance
      reboot:
