- name: Initialize Apache Spark Master
  hosts: master
  user: ubuntu
  become: yes

  vars_prompt:
    - name: spark_version
      prompt: Enter the desired Apache Spark version
      default: "3.3.1"
      private: no

    - name: node_ips
      prompt: "Enter the private IP addresses of the worker nodes, separated by spaces"
      private: no

  tasks:
    - set_fact:
        node_ips: "{{ node_ips.split(' ') }}"

    - name: Running apt update
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Installing required apt packages
      apt:
        name:
          - openjdk-8-jdk
          - scala
        state: latest

    - name: Copying id_rsa
      copy:
        src: /root/.ssh/id_rsa
        dest: /home/ubuntu/.ssh
        owner: ubuntu
        group: ubuntu
        mode: "0600"

    - name: Copying mysql-connector-j
      copy:
        src: /root/mysql-connector-j_8.0.31-1ubuntu22.04_all.deb
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu

    - name: Installing mysql-connector-j
      apt:
        deb: /home/ubuntu/mysql-connector-j_8.0.31-1ubuntu22.04_all.deb

    - name: Deleting mysql-connector-j_8.0.31-1ubuntu22.04_all.deb
      file:
        path: /home/ubuntu/mysql-connector-j_8.0.31-1ubuntu22.04_all.deb
        state: absent

    - name: Creating user named "git"
      user:
        name: git

    - name: Creating /home/git/.ssh folder
      file:
        path: /home/git/.ssh
        state: directory
        owner: git
        group: git
        mode: 0700

    - name: Copying /home/ubuntu/.ssh/authorized_keys to /home/git/.ssh/authorized_keys
      copy:
        src: /home/ubuntu/.ssh/authorized_keys
        dest: /home/git/.ssh/authorized_keys
        owner: git
        group: git
        mode: 0600
        remote_src: true

    - name: Creating bare spark git repo at /home/git/custom-spark
      shell: git init --bare /home/git/custom-spark

    - name: Change file ownership of /home/git/custom-spark
      file:
        path: /home/git/custom-spark
        owner: git
        group: git
        mode: "0744"

    - name: Downloading compressed Apache Spark file
      get_url:
        url: https://dlcdn.apache.org/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-hadoop3.tgz
        dest: /home/ubuntu/spark-{{ spark_version }}-bin-hadoop3.tgz

    - name: Extracting Apache Spark
      shell: tar xvf /home/ubuntu/spark-{{ spark_version }}-bin-hadoop3.tgz

    - name: Deleting compressed Apache Spark file
      file:
        path: /home/ubuntu/spark-{{ spark_version }}-bin-hadoop3.tgz
        state: absent

    - name: Moving Apache Spark to /usr/local/spark
      shell: mv /home/ubuntu/spark-{{ spark_version }}-bin-hadoop3 /usr/local/spark

    - name: Changing ownership of /usr/local/spark
      file:
        path: /usr/local/spark
        owner: ubuntu
        group: ubuntu

    - name: Adding spark to path in /home/ubuntu/.profile
      lineinfile:
        path: /home/ubuntu/.profile
        line: export PATH=/usr/local/spark/bin:$PATH

    - name: Creating Apache Spark slaves file
      file:
        path: /usr/local/spark/conf/slaves
        state: touch
        owner: ubuntu
        group: ubuntu
        mode: u=rw,g=r,o=r

    - name: Adding worker IPs to Apache Spark slaves file
      lineinfile:
        path: /usr/local/spark/conf/slaves
        line: "{{ item }}"
      loop: "{{ node_ips }}"

    - name: Creating symbolic link for MySQL Connector J
      shell: ln -sf /usr/share/java/mysql-connector* /usr/local/spark/jars

    - name: Rebooting the master instance
      reboot:
